DiagrammeactivitéUML
GuillaumeChamp/PLT pull request #13
Opened 2023-10-09 11:00 UTC by LNordine

Ce diagramme comporte l'ancienne version et la version UML (refaite) afin de faciliter votre relecture . J'ai éclaté le bloc de gestion des actions afin de l'explicité.

2023-10-20 11:39 UTC, GuillaumeChamp requested changes
Comme mentionné, inclure le travail de Simon

2023-10-20 16:53 UTC, LNordine commented
prout

2023-10-20 16:54 UTC, LNordine commented
il y a deux diagramme dia le bon c'est la V3. Mais teste sur l'autre si en ne gardant que la structure UML on a toujours l'erreur à l'ouverture.

2023-10-21 08:42 UTC, LNordine commented
J'ai supprimé le doublon de diagramme dia et mis à jour le diagramme une dernière fois. Cette version devrait être la version ultime.

2023-10-21 09:25 UTC, LNordine commented
Ok j'ai mis des commentaires et je dois mettre à jour le rapport

2023-10-21 09:25 UTC, GuillaumeChamp approved these changes

2023-10-21 09:28 UTC, merged