Présentation générale du jeu
GuillaumeChamp/PLT pull request #14
Opened 2023-10-12 12:12 UTC by Cinortas

Présentation des ressources, principe et règles du jeu.

2023-10-12 20:37 UTC, GuillaumeChamp requested changes

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Le jeu se joue de 2 à 7 joueurs. Les règles n'étant pas les même selon le nombre de joueur, nous faisons donc la version à 4 joueurs.
Je formulerais en : les règles variant en fonction du nombre de joueur, nous fixons la tailles la partie à 4 joueurs ce qui implique que ...
C'est peut être du chipotage

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Le joueur qui possède la couronne mélange les 8 cartes personnages. 3 cartes sont alors choisies aléatoirement puis écartées, 2 face visibles et 1 face cachée (le Roi ne peut pas se trouver dans les
Le fonctionnement du jeu n'impose pas que ce soit le premier joueur qui choisit la troisième défausse ?

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Les personnages sont appelés dans l'ordre de leur numéro. Chaque fois qu’un personnage est appelé, le joueur qui l’avait choisi révèle sa carte de personnage et joue son tour.  Si personne n’avait ch
Si **aucun** joueur

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Les joueurs jouent donc à tour de rôle, non pas dans le sens horaire habituel mais dans un ordre qui dépend des cartes de personnages qu’ils ont choisies. Lorsque le personnage d’un joueur est appelé
Pas clair, clarifie avec peut être un exemple

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +  1) Au choix: soit prendre deux pièces d'or de la banque; soit piocher deux cartes Quartier, en choisir une et se défausser de l’autre sous la pioche.
choisir une et défauser l'autre.

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +• soit vous défausser d’un certain nombre de cartes de votre main, les placer sous la pioche, et piocher le même nombre de cartes en échange.
Encore une fois, les défausser tout court quitte à faire un lexique pour expliquer la défausse

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Vous recevez une pièce d’or par quartier religieux (bleu) dans votre cité*. Vous ne pouvez pas être attaqué par le Condottiere.
Mettre condottiere et les autres termes similaire en gras avec **

2023-10-12 20:37 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Vous recevez une pièce d’or par quartier soldatesque (rouge) dans votre cité*. À la fin de votre tour, vous pouvez attaquer une cité pour y détruire un quartier de votre choix en payant le coût de ce
quartier militaire nan ?

2023-10-13 06:49 UTC, KarlLbs approved these changes

2023-10-13 11:47 UTC, Cinortas commented on rapport/rapport.md
> +Le joueur qui possède la couronne mélange les 8 cartes personnages. 3 cartes sont alors choisies aléatoirement puis écartées, 2 face visibles et 1 face cachée (le Roi ne peut pas se trouver dans les
Non à 4 joueurs ça se passe comme ça (on avait pas exactement les bonnes règles durant la partie qu'on a fait ensemble)

2023-10-13 11:53 UTC, Cinortas commented on rapport/rapport.md
> +Vous recevez une pièce d’or par quartier soldatesque (rouge) dans votre cité*. À la fin de votre tour, vous pouvez attaquer une cité pour y détruire un quartier de votre choix en payant le coût de ce
les deux sont valables mais peut etre plus courant oui, je change

2023-10-13 11:55 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Combinaison entre un jeu de gestion (type 7 Wonders) et un jeu de cartes à identité secrète (type Loups Garous de Thiercelieux)
Citadelle est un jeu de plateau au tour par tour avec gestion de ressources. Il implémente aussi un aspect role secret

2023-10-13 12:02 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Les personnages sont appelés dans l'ordre de leur numéro. Chaque fois qu’un personnage est appelé, le joueur qui l’avait choisi révèle sa carte de personnage et joue son tour.  Si personne n’avait ch
Un espace en trop

2023-10-13 12:30 UTC, GuillaumeChamp requested changes
Deux choses à peaufiner.

2023-10-13 12:30 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Le but du jeu est d'accumuler le plus de points de jeu en construisant des bâtiments dans sa cité. Le jeu s'arrête lorsqu'un des joueurs bâtit le 8e quartier de sa cité.
Et que le tour est terminé

2023-10-13 12:30 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Chaque quartier a une gemme de couleur qui indique sa catégorie (Religion = bleu, Noblesse = jaune, Commerce = vert, Militaire = rouge, Merveille = violet). Chaque quartier a un coût de construction
Chaque quartier violet (appelé Merveille)

2023-10-13 13:56 UTC, GuillaumeChamp approved these changes

2023-10-13 13:57 UTC, merged