Rapport engine
GuillaumeChamp/PLT pull request #37
Opened 2023-11-27 14:44 UTC by LNordine

2023-11-27 17:24 UTC, GuillaumeChamp requested changes
Des petits changement à faire et des éléments à compléter concernant le traitement des commandes

2023-11-27 17:24 UTC, GuillaumeChamp commented on rapport/rapport.md
> +Les changements d’état ne suivent pas d’horloge globale, chaque état sera mis à jour à l’issu d'exécutions de commandes par le joueur vers l’engine ou par l’engine vers le joueur.
Formulation maladroite mais tout les éléments sont là
de l'engine au joueur

2023-11-27 17:24 UTC, GuillaumeChamp commented on rapport/rapport.md
> +**4.1 Changements extérieurs**
commandes externes ?

2023-11-27 17:24 UTC, GuillaumeChamp commented on rapport/rapport.md
> +**4.2 Changements autonomes**
commandes internes ?

2023-11-27 17:24 UTC, GuillaumeChamp commented on rapport/rapport.md
> +ChangPhaseCommand : Une command de changemnt de phase.
ok

2023-11-28 07:26 UTC, KarlLbs commented on rapport/rapport.md
> +**4.1 Changements extérieurs**
C'est écrit comme ça dans l'exemple de rapport

2023-11-28 07:27 UTC, KarlLbs commented on rapport/rapport.md
> +**4.2 Changements autonomes**
pareil

2023-12-04 10:38 UTC, merged