ChangePhase, End of turn,GainGold StartGame
GuillaumeChamp/PLT pull request #60
Opened 2023-12-15 10:45 UTC by LNordine

2023-12-19 12:54 UTC, GuillaumeChamp requested changes

2023-12-19 12:54 UTC, GuillaumeChamp commented on src/shared/engine/ChooseCharacterCommand.cpp
Compléter Check

2023-12-19 12:54 UTC, GuillaumeChamp commented on src/shared/engine/EndOfTurnCommand.cpp
> +
Call change phase

2023-12-19 12:54 UTC, GuillaumeChamp commented on src/shared/engine/GainGoldCommand.cpp
> +          return Command::check(state);
check à compléter

2023-12-19 12:54 UTC, GuillaumeChamp commented on src/shared/engine/StartGameCommand.cpp
> +
Commande vide, est-ce normal ?

2023-12-19 13:20 UTC, KarlLbs commented on src/client/main.cpp
> +            //gameEngine->executeAllCommands();
DEAD CODE

2023-12-20 13:39 UTC, LNordine commented on src/shared/engine/EndOfTurnCommand.cpp
> +
Si l'auteur de la commande est le lastPlayer alors on lance une commande de changement de phase.

2023-12-20 13:43 UTC, LNordine commented on src/shared/engine/GainGoldCommand.cpp
> +          return Command::check(state);
La commande GainGold ne s'executera que si isDrawable=true. Lors de l'execution de la commande IsDrawable passe à false. Cette commande ne peut donc s'executer qu'une fois par tour. En effet lors du endofturn je réinitialise le IsDrawable=true.

2023-12-20 13:44 UTC, LNordine commented on src/shared/engine/StartGameCommand.cpp
> +
Oui je peut la compléter dés que possible maintement.

2023-12-22 09:51 UTC, GuillaumeChamp requested changes
Deux trois optimisations à faire

2023-12-22 09:51 UTC, GuillaumeChamp commented on src/shared/engine/ChooseCharacterCommand.cpp
> +        if (it != availableCharacters.end()) { characterIsAvaible=true;}
optimisation au niveau des bool

2023-12-22 09:51 UTC, GuillaumeChamp commented on src/shared/engine/EndOfTurnCommand.cpp
> +            currentPlayer = static_cast<state::PlayerId>((static_cast<int>(currentPlayer)%4) + 1 );
ligne de code à factoriser

2023-12-24 10:16 UTC, closed without merging

2023-12-24 10:17 UTC, GuillaumeChamp commented
PR mergé par mes soins