Finishing all the drawing cards commands
GuillaumeChamp/PLT pull request #74
Opened 2024-01-08 18:00 UTC by KarlLbs

2024-01-08 19:25 UTC, GuillaumeChamp requested changes
Corriger les tests et traiter le retours

2024-01-08 19:25 UTC, GuillaumeChamp commented on src/shared/engine/ChooseCardCommand.cpp
> +        // The player has another card to draw choose after this one so we stay in Draft subphase
J'ai l'impressions que c'est pas ce que l'on veut.
On s'attend à prendre une carte et à l'enlever de la liste puis de continuer à demander de choisir une carte parmi les deux restantes

2024-01-08 19:25 UTC, GuillaumeChamp commented on src/shared/engine/ChooseCardCommand.cpp
> +    if (nbOfDrawableCards == 3) // If there are 3 possible cards to draw from, it means the player has an Observatory
Quid du cas de l'architecte ?

2024-01-08 19:25 UTC, GuillaumeChamp commented on src/shared/engine/PlayCardCommand.cpp
Peut être changer le nom de cette commande mais elle est ok

2024-01-08 19:25 UTC, GuillaumeChamp commented on src/shared/engine/DrawCommand.cpp
> +        if (card.getNameOfCard() == "Observatoire") {
NON !
le nom de la carte c'est l'ID telle qu'indiquée dans le csv

2024-01-08 19:25 UTC, GuillaumeChamp commented on src/shared/engine/DrawCommand.cpp
> +    int nbOfCards;
int nbOfCard = 2 et tu enlève le if d'après

2024-01-08 19:25 UTC, GuillaumeChamp commented on src/shared/engine/DrawCommand.cpp
> -    state.updatePlayer(player);
il manque la désactivation de la pioche et du pouvoir si utilisé

2024-01-09 14:42 UTC, KarlLbs commented on src/shared/engine/ChooseCardCommand.cpp
> +    if (nbOfDrawableCards == 3) // If there are 3 possible cards to draw from, it means the player has an Observatory
Le cas de l'architecte est traité directement dans DrawCommand puisque son pouvoir ne nécessite pas de choisir une carte (il en pioche juste deux)

2024-01-09 14:43 UTC, KarlLbs commented on src/shared/engine/PlayCardCommand.cpp
Je la change en GetCardCommand ?

2024-01-09 14:46 UTC, KarlLbs commented on src/shared/engine/DrawCommand.cpp
> +        if (card.getNameOfCard() == "Observatoire") {
Bah pourtant c'est le name est bien un std::string ? Et dans tes tests du state c'est bien des strings ? Je ne comprends pas

2024-01-09 14:57 UTC, KarlLbs commented on src/shared/engine/DrawCommand.cpp
> -    state.updatePlayer(player);
J'ai ajouté la désactivation du pouvoir. Où est-ce qu'il manque une désactivation de la pioche ?

2024-01-09 15:30 UTC, KarlLbs commented on src/shared/engine/ChooseCardCommand.cpp
> +        // The player has another card to draw choose after this one so we stay in Draft subphase
J'ai oublié de l'enlever de la liste effectivement, ça devrait être bon maintenant

2024-01-09 16:08 UTC, GuillaumeChamp approved these changes

2024-01-09 16:08 UTC, merged